### ISSUE TITLE
ТЗ

### ISSUE THREAD

**Issue by Shtandart** [Shtandart/CourseProject-Diploma-#1]

**Comment by wldmr-key** [comment]
Для начала следовало бы определиться с темой. Дележка с МИМАПР - вопрос технический и легко решаемый.
Обе темы неплохи. Так что выбирай ту, по которой сможешь написать вменяемую программу

**Comment by Shtandart** [comment]
[ТЗ.docx](https://github.com/Shtandart/CourseProject-Diploma-/files/3721832/default.docx)

**Comment by wldmr-key** [comment]
пойдет...
давай, дальше ))
