### ISSUE TITLE
Написать задание на выполнение курсовой работы

### ISSUE THREAD

**Issue by wldmr-key** [Shtandart/CourseProject-Diploma-#2]
и побыстрее))

**Comment by Shtandart** [comment]
[ТЗ.docx](https://github.com/Shtandart/CourseProject-Diploma-/files/3614185/default.docx)

**Comment by wldmr-key** [comment]
)) вообще-то задача была такой - выбрать тему и заполнить бланк на одной страничке

Но, раз уж, ты осилил ТЗ, то первые вопросы - а откуда ты берешь сведения для своей системы? У тебя одна авиакомпания или несколько? Ты являешься монополистом по продаже билетов? В какой стране ты действуешь и знаешь ли ты ее законы?

**Comment by Shtandart** [comment]
Базу данных я собираюсь сделать самостоятельно, потому что цены в основном варьируются, так же как и пункты назначения. Да в планах сделать несколько авиакомпаний у которых есть самолёты, которые будет перевозить пассажиров. Немного не понимаю суть монополии в вашем вопросе, если существуют другие места по продаже билетов или вы имеете ввиду как моя система будет считаться с ними? Про законы - я условно понимаю как оно работает, но я этим планировал заняться в исследовательской части, надо будет почитать про это, я понимаю что какой то процент с продаж придётся отдавать государству

**Comment by wldmr-key** [comment]
ок, исследуй и дописывай ТЗ
