### ISSUE TITLE
Новое ТЗ

### ISSUE THREAD

**Issue by Shtandart** [Shtandart/CourseProject-Diploma-#5]
В общем, мою тему на диплом не одобрил Евгений Владимирович, поэтому я с ним обсудил новую и он её принял.

**Comment by Shtandart** [comment]
Тема "Разработка веб-приложения для поиска работы с использованием геолокации". Сама по себе идея заключается в том что люди оставляют заявку на какую то категорию работ: строительные, быстрая работа (одноразовая), ремонт и тд. Люди могут искать подходящее предложение на основе рейтинга работодателя и исполнителя, а так же оставлять свои портфолио.

**Comment by Shtandart** [comment]
[ТЗ.docx](https://github.com/Shtandart/CourseProject-Diploma-/files/3835708/default.docx)

**Comment by Shtandart** [comment]
[ТЗ.docx](https://github.com/Shtandart/CourseProject-Diploma-/files/3936506/default.docx)
Исправленная версия, теперь без реализации функций билетов)

**Comment by wldmr-key** [comment]
нормально, пойдет
