### ISSUE TITLE
Концептуальная схема данных

### ISSUE THREAD

**Issue by Shtandart** [Shtandart/CourseProject-Diploma-#6]

**Comment by Shtandart** [comment]
![image](https://user-images.githubusercontent.com/43147636/70469029-4d942000-1ad9-11ea-8dbe-352b2ea93ece.png)

**Comment by Shtandart** [comment]
Не очень уверен насчёт связей с Рейтингом. И задумался над использованием атрибута лимита для работы, когда на заявку нужно набрать нескольких работников.

**Comment by wldmr-key** [comment]
хорошо
- мне кажется (возможно, я не прав), что для заявок должен быть статус актуальности (хотя, может, он определяется датой)

- у рейтинга с пользователем две связи один к многим - одна для исполнителя, другая для заказчика

- не думаю, что у пользователя может быть только одно резюме  - заказчик может иметь несколько профилей деятельности, да и исполнитель тоже

- связь между резюме и работой для исполнителей - неправильная. Как отразить тот факт, что на одну работу претендуют несколько исполнителей? Как отразить тот факт, чот на эту работу выбрали одного (или нескольких)?

**Comment by Shtandart** [comment]
Насчёт связи исполнителей с работой - идея была такая, что исполнители видят эту вакансию и видят как раз таки список претендентов с рейтингом на эту самую работу, возможно стоит добавить в Работу атрибут списка претендентов и лимита. Либо же выделить как отдельную сущность.

**Comment by wldmr-key** [comment]
ну, сделай, уж, как нибудь!

**Comment by Shtandart** [comment]
![image](https://user-images.githubusercontent.com/43147636/70560934-965fdd80-1b9a-11ea-975e-78e85d5e7ae8.png)
Вот так предварительно

**Comment by wldmr-key** [comment]
нет. У тебя по-прежнему на работу только один исполнитель. Вообще распределение атрибутов между заявкой и работой тебе стоит продумать получше
связи между рейтингом и пользователем должны быть направлены в другую сторону (если я правильно понимаю - по каждой работе они проставляются, то есть у пользователя должно быть много рейтингов, а не наоборот)

**Comment by Shtandart** [comment]
![image](https://user-images.githubusercontent.com/43147636/70866390-1ced3400-1f7a-11ea-8759-5d7da412b39e.png)
Поправил связи с рейтингом, немного переставил атрибуты у работы и заявки, связь исполнителя и работы сделал многое ко многим, то есть на работу претендуют один или несколько

**Comment by wldmr-key** [comment]
а, где информация о том, кто получил работу из подавших резюме?

**Comment by Shtandart** [comment]
![image](https://user-images.githubusercontent.com/43147636/70867764-11096e00-1f8a-11ea-8367-cfaf80bd3415.png)
Добавил атрибут статус для резюме (на рассмотрении, принятое и отклонённое)

**Comment by wldmr-key** [comment]
оле! у тебя бедный соискатель под каждую работу пишет резюме? Тогда между работами и резюме отношение 1:1. Все проще!

**Comment by Shtandart** [comment]
Внёс правки, создал скрытую сущность статуса отправки резюме (вроде бы она пунктиром обозначается). В сущности Работа оставил только атрибут статуса выполнения, все остальные поместил в заявку
![image](https://user-images.githubusercontent.com/43147636/71263217-88584c80-2352-11ea-94ca-2584607ffa42.png)

**Comment by wldmr-key** [comment]
из всего этого возникает вопрос - а нужна ли сущность "работа"? Я могу обосновать ее востребованность (с несколько другим атрибутным составом) а ты можешь? Если нет, то при настоящей защите она тебя потопит...
У статуса отправки все связи должны быть "много к одному". Подумай, почему...

**Comment by Shtandart** [comment]
Переделал связь, ну как я понял у одной работы есть "много" резюме с "много" статусами.
![image](https://user-images.githubusercontent.com/43147636/71312693-ca5ebc80-243e-11ea-8dbc-96af3da05eae.png)
Насчёт сущности работа не очень понимаю как поступить, все атрибуты перешли заявке, если убирать её из схемы и считать, что заявка это и есть работа, то очень большой список атрибутов получается. А что-то новое не приходит на ум, отличающее её от заявки.

**Comment by wldmr-key** [comment]
когда кого-то смущал большой список атрибутов? )) у меня были таблицы с сотнями атрибутов...
работа, как отдельная сущность имеет смысл, когда ты одну и ту же заявку помещаешь на разные сроки. Но это, думаю, не твой случай. Так что избавляйся, наверное, от нее. Не сейчас, так на дипломе ))

**Comment by Shtandart** [comment]
В конечном итоге схема должна как то так выглядеть ?
![image](https://user-images.githubusercontent.com/43147636/71326124-6e139f80-2507-11ea-9581-f7d10f2c17ef.png)

**Comment by wldmr-key** [comment]
да, очень близко. Во всяком случае, я ошибок не увидел
