### ISSUE TITLE
UML диаграммы

### ISSUE THREAD

**Issue by Shtandart** [Shtandart/CourseProject-Diploma-#7]

**Comment by Shtandart** [comment]
Хотел поподробнее спросить подойдёт ли такое оформление и сценарии. И еще один вопрос, как и где описать расширенные пользовательские сценарии работы? Вот для сценария "Поиска необходимой работы", например. То есть предварительно пользователь для этого должен пройти во вкладку "Категорий" и далее с помощью фильтров найти что-то подходящее для себя. Я так понимаю я должен это где-то сбоку рядом с соответствующим сценарием написать.
![image](https://user-images.githubusercontent.com/43147636/71263320-b89feb00-2352-11ea-94e0-130064b11227.png)

**Comment by wldmr-key** [comment]
приведенный пример - это простой экстент. Почитай тут - https://www.intuit.ru/studies/courses/1007/229/lecture/5962 
Картинка нормальная. Только у заказчика - не поиск (он не ищет), а отбор необходимых работников

**Comment by Shtandart** [comment]
Почитал насчёт экстентов и инклудов. Теперь уже более правильно задам свой вопрос, а необходимо ли все эти сценарии описывать с помощью этих механик? Если у исполнителя и заказчика есть одинаковые сценарии (регистрация, вход в систему и создание резюме) нужно ли делать общую диаграмму для них?

**Comment by wldmr-key** [comment]
"необходимо ли" - нет. Но, если ты нарисуешь хоть один вменяемый экстент, ты произведешь лучшее впечатление ))
Как ты думаешь, для исполнителя отправление резюме на работу является самостоятельным действием или следствием поиска?
"нужно ли делать общую диаграмму" - это твой выбор. Я бы не стал

**Comment by Shtandart** [comment]
Ну если исходить из того, что исполнитель может отправить резюме только после того, как он что-то нашёл, то скорее всего это следствие поиска.

**Comment by wldmr-key** [comment]
И? Не является ли отправка резюме экстентом поиска?
Проанализируй все остальные активности подобным образом

**Comment by Shtandart** [comment]
В примере из лекции не указывалось про последовательные экстенты, то есть последующий возникает из предыдущего. Правильно ли я сделал со сценарием "Поиска необходимой работы"? Сценарий "Оценки заказчика" происходит, когда работа выполнится исполнителем. Думаю никаких расширений для этого сценария больше не требуется. 
![image](https://user-images.githubusercontent.com/43147636/71326347-69041f80-250a-11ea-861b-7c0afb63fbd6.png)

**Comment by wldmr-key** [comment]
ты принял мою подсказку за решение. между поиском и отправкой резюме отношение extend или include? Впрочем, еще немного подумаешь над проблемой и точно станешь большим специалистом, чем я в диаграммах прецедентов ))

**Comment by Shtandart** [comment]
Перечитал еще раз различия между ними, я так понимаю что использование экстент дополняет в моём случае все сценарии до отправки резюме (переход на соответствующую вкладку и использование фильтров). А уже само отправление резюме является исполнением поиска необходимой работы и "включается" туда. Получается это инклуд.

**Comment by Shtandart** [comment]
Надеюсь не слишком напутал. Сомневаюсь в отборе и анализе на диаграмме заказчика, но как мне кажется это включение другого прецедента.
![image](https://user-images.githubusercontent.com/43147636/71375317-dda09200-25ce-11ea-9487-6f8e94bcf597.png)
![image](https://user-images.githubusercontent.com/43147636/71375341-f27d2580-25ce-11ea-84fd-a525fb7df9de.png)

**Comment by wldmr-key** [comment]
нормально, дальше не улучшай
